### ISSUE TITLE
Convenience Kinetics Process Fails Because of Incorrect setup.py

### ISSUE THREAD

**Issue by U8NWXD** [vivarium-collective/convenience-kinetics#1]
Right now, using the `convenience_kinetics.py` process results in the following error:

```text
File "/vivarium_convenience/processes/convenience_kinetics.py", line 40, in <module>
    from vivarium_convenience.library.kinetic_rate_laws import KineticFluxModel
ModuleNotFoundError: No module named 'vivarium_convenience.library'
```

This is because we don't include `vivarium_convenience.library` as a package in `setup.py`:

https://github.com/vivarium-collective/convenience-kinetics/blob/29f9d10a705b8f9d5c5d174d2437dd219106653d/setup.py#L12-L17

**Comment by eagmon** [comment]
Your fix looks good! I'll merge it in.
